### ISSUE TITLE
Problem updating Fastlane to latest

### ISSUE THREAD

**Issue by grantkemp** [fastlane/setups#13]
Looks like it won't let me update via gem higher than V 1.98 

```
1.99.0 Improvements
* Get default value for `teamid` from Appfile in `update_project_team` action (#5478)
* Get default value for `teamid` from Appfile in `update_app_identifier` action (#5465)
* Add `commit` option to `add_git_tag` action (#5466)
* Add option for `carthage` action to pass in specific dependencies to update (#5500)
* Ignore `platform` option case for `carthage` action (#5504)
* Add `strategy` option to `hockey` action (#5514)
```

> Update using 'sudo gem update fastlane'
> Fruit:xxxxxxxxx$ sudo gem update fastlane
> Updating installed gems
> Nothing to update

Repeatable steps: 
1. install via the Mac App 
2 If I install via command line it appears to work ok using the install --verbose

**Comment by mfurtak** [comment]
Hi @grantkemp - thanks for the report! 👍 

Ah, yes - I see the confusion. The version of fastlane installed by the Fabric Mac app is special in that it is not installed like a normal Ruby gem, so your `gem` command likely can't tell that you have fastlane installed at all.

The Fabric Mac app can update your installation of fastlane if you head back to that tab therein.

Let me know if you run into any trouble 🚀
