### ISSUE TITLE
i'm using the fabric app to distribute beta. is this different from testflight?

### ISSUE THREAD

**Issue by rlam3** [fastlane/setups#15]
i'm using the fabric app to distribute beta. is this different from testflight?

**Comment by mfurtak** [comment]
Hi @rlam3 - Yes, it is different! The Fabric app distributes your beta builds through Beta by Crashlytics, which you can find through your Fabric web dashboard.

**Comment by rlam3** [comment]
Hi @mfurtak - what are the tradeoff between testflight and fastlane?

**Comment by mfurtak** [comment]
That will depend on your needs. :smile: If you'd like to discuss how to get the most out of using Beta by Crashlytics, I'd suggest contacting support@fabric.io 👍
